server:
  port: 8080  # Порт Film-Service

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: film-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: film-service  # Имя сервиса для регистрации в Eureka

  datasource:
    url: jdbc:postgresql://localhost:5432/film_db
    username: postgres
    password: qwerty1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Показывать SQL-запросы в логах

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
    # Отключаем дефолтную секьюрность и security для Actuator

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

tmdb:
  api_key: e28fe83118014486bd75c60ecd32ede4
  base_url: https://api.themoviedb.org/3


